version: '3.8'

services:
  # PostgreSQL Database for Explorer
  postgres:
    image: postgres:15
    container_name: ergo-postgres
    environment:
      POSTGRES_DB: ergo_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - explorer-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - explorer-net

  shark-indexer:
    build:
      context: ./shark-indexer
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ergo_explorer
      - DB_USER=postgres
      - DB_PASSWORD=password
      - NODE_URL=http://192.168.1.195:9053
      - REDIS_HOST=redis
      - CONNECTION_TIMEOUT=30000
      - READ_TIMEOUT=30000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./shark-indexer:/app
    networks:
      - explorer-net

volumes:
  postgres-data:
  redis-data:

networks:
  explorer-net:
    name: explorer-net